#!/usr/bin/env bash
# archive-gallery.sh — make ephemeral evidence/gallery durable for OpenSpec archive.
# Usage:
#   ./scripts/archive-gallery.sh              # stage + archive copy
#   ./scripts/archive-gallery.sh --stage-only # only stage under openspec/changes/add-visual-validation/evidence/gallery
#   ./scripts/archive-gallery.sh --help
#
# Ephemeral source: evidence/gallery/ (gitignored, generated by `cargo run --bin snapshot-gallery`
# or `cargo test -- --generate-gallery`). This script copies HTML + ANSI sidecars into:
#  1. openspec/changes/add-visual-validation/evidence/gallery/ — staged copy that
#     `openspec archive add-visual-validation` will carry into the archive automatically
#     (since archive copies the whole change folder).
#  2. openspec/changes/archive/add-visual-validation/evidence/gallery/ — direct archive
#     destination for manual verification / idempotent re-runs (also covers dated prefix
#     variants like 2026-08-24-add-visual-validation if present).
#
# Keep evidence/gallery/ gitignored; committed mirror lives under openspec/changes/**/evidence/gallery/.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/evidence/gallery"
STAGED="$ROOT/openspec/changes/add-visual-validation/evidence/gallery"
ARCHIVE="$ROOT/openspec/changes/archive/add-visual-validation/evidence/gallery"

usage() {
  cat <<'USAGE'
archive-gallery.sh — copy ephemeral evidence/gallery into durable OpenSpec archive

  ./scripts/archive-gallery.sh              copy to staged + archive destinations
  ./scripts/archive-gallery.sh --stage-only copy only to staged (pre-archive) location
  ./scripts/archive-gallery.sh --help       this help

Source must exist; generate it first with:
  cargo run --bin snapshot-gallery
  # or
  cargo test -- --generate-gallery
USAGE
}

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  usage
  exit 0
fi

STAGE_ONLY=0
if [[ "${1:-}" == "--stage-only" ]]; then
  STAGE_ONLY=1
fi

# Ensure source exists — try to generate if missing.
if [[ ! -d "$SRC" || ! -f "$SRC/index.html" ]]; then
  echo "archive-gallery: $SRC/index.html missing — generating via cargo run --bin snapshot-gallery..." >&2
  if command -v cargo >/dev/null 2>&1; then
    (cd "$ROOT" && cargo run --bin snapshot-gallery)
  fi
fi

if [[ ! -f "$SRC/index.html" ]]; then
  echo "error: source gallery not found at $SRC/index.html — run 'cargo run --bin snapshot-gallery' first" >&2
  exit 1
fi

# Stage copy (survives `openspec archive` which copies the change folder)
mkdir -p "$STAGED"
cp -r "$SRC"/* "$STAGED"/
echo "staged  $SRC -> $STAGED ($(ls -1 "$STAGED" | wc -l) files)"

if [[ "$STAGE_ONLY" -eq 1 ]]; then
  echo "stage-only: skipping archive destination"
  exit 0
fi

# Direct archive copy (idempotent, for verification after archive)
mkdir -p "$ARCHIVE"
cp -r "$SRC"/* "$ARCHIVE"/
echo "archived $SRC -> $ARCHIVE ($(ls -1 "$ARCHIVE" | wc -l) files)"

# Also copy to dated archive variants if they exist (e.g. 2026-08-24-add-visual-validation)
for dated in "$ROOT"/openspec/changes/archive/*add-visual-validation; do
  # glob returns literal when no match with nullglob off; skip non-dirs and the canonical dir
  [[ -d "$dated" ]] || continue
  [[ "$dated" == "$ROOT/openspec/changes/archive/add-visual-validation" ]] && continue
  mkdir -p "$dated/evidence/gallery"
  cp -r "$SRC"/* "$dated/evidence/gallery"/
  echo "archived $SRC -> $dated/evidence/gallery ($(ls -1 "$dated/evidence/gallery" | wc -l) files)"
done

# Verify
if [[ -f "$ARCHIVE/index.html" ]]; then
  echo "verify: $ARCHIVE/index.html present"
else
  echo "verify: $ARCHIVE/index.html MISSING" >&2
  exit 1
fi
if [[ -f "$STAGED/index.html" ]]; then
  echo "verify: $STAGED/index.html present"
else
  echo "verify: $STAGED/index.html MISSING" >&2
  exit 1
fi

echo "done."
