#!/usr/bin/env python3
"""Generate fixtures/own_scale.ini: a large original synthetic patch.

~500 sections / ~500 cables off one bare [p2b8]: 8 button circuits with
preamble labels (seeds the label-guess path), lfo clock seeds, and long
chained [copy] runs split across named banners (seeds cluster rendering).
All circuits/params exist in the DROID schema so validation reports no
Error findings and the patch loads cleanly.
"""

from pathlib import Path

N_GROUPS = 6
COPIES_PER_GROUP = 80  # 6*80=480 copies + 8 buttons + 6 lfos + 1 p2b8 = 495 sections

out = []
out.append("# Own scale fixture: generated by scripts/gen_own_scale.py.")
out.append("# Original synthetic content for graph/layout/optimizer scale tests.")
out.append("")
for i in range(1, 9):
    out.append(f"# B1.{i}: [OWNBTN{i}]")
out.append("")
out.append("[p2b8]")
out.append("")

cable = 0


def new_cable():
    global cable
    name = f"_OWNS{cable}"
    cable += 1
    return name


for g in range(N_GROUPS):
    out.append(f"# ---- Own chain {g + 1} ----")
    out.append("")
    seed = new_cable()
    out.append("[lfo]")
    out.append("    hz = 2")
    out.append(f"    square = {seed}")
    out.append("")
    prev = seed
    for _ in range(COPIES_PER_GROUP):
        nxt = new_cable()
        out.append("[copy]")
        out.append(f"    input = {prev}")
        out.append(f"    output = {nxt}")
        out.append("")
        prev = nxt
    # Terminate the chain on a hardware jack so no cable dangles.
    out.append("[copy]")
    out.append(f"    input = {prev}")
    out.append("    output = O1")
    out.append("")

for i in range(1, 9):
    out.append("[button]")
    out.append(f"    button = B1.{i}")
    out.append(f"    led = L1.{i}")
    out.append(f"    output = _OWNTRIG{i}")
    out.append("")
    out.append("[copy]")
    out.append(f"    input = _OWNTRIG{i}")
    out.append("    output = O1")
    out.append("")

path = Path(__file__).resolve().parent.parent / "fixtures" / "own_scale.ini"
path.write_text("\n".join(out))
print(f"wrote {path}: {sum(1 for l in out if l.startswith('['))} sections")
