pub mod app;
pub mod config;
pub mod diff;
pub mod events;
pub mod expression;
pub mod favorites;
pub mod geometry;
pub mod graph;
pub mod graph_anim;
pub mod graph_render;
pub mod gui;
pub mod handler;
pub mod help;
pub mod latency;
pub mod layout;
pub mod optimize;
pub mod panes;
pub mod patch;
pub mod performance;
pub mod physical;
pub mod plugin;
pub mod rendermetrics;
pub mod schema;
pub mod sysex;
pub mod theme;
pub mod validation;

#[cfg(test)]
pub mod regression;
